### ISSUE TITLE
I can't stop wifi self-connection when dpt wake up

### ISSUE THREAD

**Issue by yefeiyu** [HappyZ/dpt-tools#75] opened 2019-03-15 05:42 UTC
Every time I manually turn off wifi.
But whenever `dpt` wakes up, wifi is automatically connected. In the android settings option, the relevant settings for the manual have been set.
How should we do?

**Comment by HappyZ** [comment] 2019-03-17 19:06
if you turned wifi off in android settings, does it also turn back on? this is weird.. it may be caused by inconsistency between DPT's app and android's app..

**Comment by yefeiyu** [comment] 2019-03-31 14:41
Yes，whenever I turned off wifi in android settings or official settings, it does also turn back on when the device wake up from sleeping.

**Comment by HappyZ** [comment] 2019-04-03 05:42
are you sure after you turned it off, it is actually off? what does the logcat say when you turn it off/on?

**Comment by HappyZ** [comment] 2019-05-18 04:56
closed as there's no further discussions

**Closed as completed by HappyZ** 2019-05-18 04:56 UTC
Labels: Question
