### ISSUE TITLE
Fujitsu rebranded the Sony Digital Paper. New firmware.

### ISSUE THREAD

**Issue by cypresstwist** [HappyZ/dpt-tools#146] opened 2019-12-04 13:00 UTC
Please see this: [https://goodereader.com/blog/electronic-readers/fujitsu-quaderno-a5-and-a4-are-rebranded-sony-digital-papers](https://goodereader.com/blog/electronic-readers/fujitsu-quaderno-a5-and-a4-are-rebranded-sony-digital-papers)

> Fujitsu is getting into digital note taking devices in Japan with the A5 and A4, which are rebranded Sony Digital Papers. They have revised the Android operating system so it is different and it does not need any apps to transfer content to and from the device, which should appeal to some. [...] The software is more or less the same, except it has a different UI. You can copy edited PDF files from your MAC/PC/Smartphone to the Quaderno, without the need of a dedicated app.

If we can get our hands on the firmware the documenttransfer part could prove useful.

**Comment by HappyZ** [comment] 2019-12-06 09:27
Interesting read. Only if someone in Japan would know this I guess. Thanks for mentioning.

**Comment by eonminion** [comment] 2020-03-01 23:14
I believe this is the downloading link: https://www.fmworld.net/digital-paper/support/download/dppfw/

P.S.
Is there a wechat group for sony digital paper?

**Comment by mleitman** [comment] 2021-01-21 20:58
I see that goodereader offers the Quaderno with android functionality added.  Do you know if it's using your method?

**Comment by HappyZ** [comment] 2022-11-18 07:53
Duplicate of #181

**Closed as completed by HappyZ** 2022-11-18 07:53 UTC
Labels: Help Needed
